---
AWSTemplateFormatVersion: '2010-09-09'
Description: Overarching CF Template to Create AEM Stack Manager Resources Stacks
Outputs:
  InstanceProfilesStackArn:
    Description: Instance Profiles Stack ARN
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-InstanceProfilesStackName
    Value:
      Ref: InstanceProfilesStack
  StackManagerStackArn:
    Description: Stack Manager Stack ARN
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-StackManagerStackName
    Value:
      Ref: StackManagerStack
  UtilitiesStackArn:
    Description: Utilities Stack ARN
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-UtilitiesStackName
    Value:
      Ref: UtilitiesStack
Parameters:
  AWSEncryptionParameters:
    Description: "A list of AWS Encyrption parameters.\nList must contain the following\
      \ values in the following order:\n  - KMS Key ID used for DynamoDB encryption\n\
      \  - KMS Key ID used for SNS-Topic & SNS Queue encryption\n  - KMS Key ARN used\
      \ for Lambda function environment variable encryption\n  - Managed Policy ARN\
      \ for SNS  encryption\n  - Managed Policy ARN for DynamoDB encryption\n  - Managed\
      \ Policy ARN for Lambda encryption\n  - Managed Policy ARN for accessing S3\
      \ CMK\n"
    Type: List<String>
  AWSNotificationParameters:
    Description: "A list of AWS notification parameters.\nList must contain the following\
      \ values in the following order:\n  - Notification email address, if the value\
      \ is 'overwrite-me' then it's considered to be disabled\n  - Notification https\
      \ URL, if the value is 'overwrite-me' then it's considered to be disabled\n"
    Type: List<String>
  AWSRegion:
    Description: Name of the AWS region
    Type: String
  CloudWatchS3StreamBucketNameParameter:
    Description: Bucket name that stores Stack data file
    Type: String
  CloudWatchS3StreamPrefixParameter:
    Description: Prefix within the Bucket to Locate Files
    Type: String
  DataBucketNameParameter:
    Description: Bucket name that stores Stack data file
    Type: String
  DynamoDBTTLAttribute:
    Default: ttl
    Type: String
  LiveSnapshotsPurgeMaxAge:
    Description: Parameters for Purging Live Snapshot in JSON Formatted String
    Type: String
  LiveSnapshotsPurgeSchedule:
    Description: CloudWatch Event Rule Schedule to Purge Old Live Snapshots
    Type: String
  MainStackPrefixParameter:
    Description: The AEM Stack Main Resources Stack Prefix
    Type: String
  OfflineSnapshotsPurgeMaxAge:
    Description: Parameters for Purging Offline Snapshot in JSON Formatted String
    Type: String
  OfflineSnapshotsPurgeSchedule:
    Description: CloudWatch Event Rule Schedule to Purge Old Offline Snapshots
    Type: String
  OrchestrationSnapshotsPurgeMaxAge:
    Description: Parameters for Purging Orchestration Snapshot in JSON Formatted String
    Type: String
  OrchestrationSnapshotsPurgeSchedule:
    Description: CloudWatch Event Rule Schedule to Purge Old Orchestration Snapshots
    Type: String
  S3DataStackManagerPrefix:
    Description: Prefix within the Bucket to Locate Files
    Type: String
Resources:
  InstanceProfilesStack:
    Properties:
      Parameters:
        AWSEncryptionParameters:
          Fn::Join:
            - ','
            - Ref: AWSEncryptionParameters
        CloudWatchS3StreamBucketNameParameter:
          Ref: CloudWatchS3StreamBucketNameParameter
        CloudWatchS3StreamPrefixParameter:
          Ref: CloudWatchS3StreamPrefixParameter
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        MainStackPrefixParameter:
          Ref: MainStackPrefixParameter
        S3DataStackManagerPrefix:
          Ref: S3DataStackManagerPrefix
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/instance-profiles.yaml
    Type: AWS::CloudFormation::Stack
  PrerequisitesStack:
    Properties:
      Parameters:
        AWSEncryptionParameters:
          Fn::Join:
            - ','
            - Ref: AWSEncryptionParameters
        AWSNotificationParameters:
          Fn::Join:
            - ','
            - Ref: AWSNotificationParameters
        MainStackPrefixParameter:
          Ref: MainStackPrefixParameter
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/prerequisites.yaml
    Type: AWS::CloudFormation::Stack
  SSMCommandsStack:
    Properties:
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/ssm-commands.yaml
    Type: AWS::CloudFormation::Stack
  StackManagerStack:
    DependsOn:
      - InstanceProfilesStack
      - PrerequisitesStack
    Properties:
      Parameters:
        AWSEncryptionParameters:
          Fn::Join:
            - ','
            - Ref: AWSEncryptionParameters
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        DynamoDBTTLAttribute:
          Ref: DynamoDBTTLAttribute
        MainStackPrefixParameter:
          Ref: MainStackPrefixParameter
        S3DataStackManagerPrefix:
          Ref: S3DataStackManagerPrefix
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/stack-manager.yaml
    Type: AWS::CloudFormation::Stack
  UtilitiesStack:
    DependsOn:
      - InstanceProfilesStack
      - PrerequisitesStack
    Properties:
      Parameters:
        AWSEncryptionParameters:
          Fn::Join:
            - ','
            - Ref: AWSEncryptionParameters
        AWSRegion:
          Ref: AWSRegion
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        LiveSnapshotsPurgeMaxAge:
          Ref: LiveSnapshotsPurgeMaxAge
        LiveSnapshotsPurgeSchedule:
          Ref: LiveSnapshotsPurgeSchedule
        MainStackPrefixParameter:
          Ref: MainStackPrefixParameter
        OfflineSnapshotsPurgeMaxAge:
          Ref: OfflineSnapshotsPurgeMaxAge
        OfflineSnapshotsPurgeSchedule:
          Ref: OfflineSnapshotsPurgeSchedule
        OrchestrationSnapshotsPurgeMaxAge:
          Ref: OrchestrationSnapshotsPurgeMaxAge
        OrchestrationSnapshotsPurgeSchedule:
          Ref: OrchestrationSnapshotsPurgeSchedule
        S3DataStackManagerPrefix:
          Ref: S3DataStackManagerPrefix
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/utilities.yaml
    Type: AWS::CloudFormation::Stack
